server:
  port: 8083

spring:
  cloud:
#    config:
#      import-check:
#        enabled: false
  datasource:
#    url: jdbc:mysql://localhost:3306/product-service?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://${DB_HOST:localhost}:3306/product-service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296

management:
  tracing:
    sampling:
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/zipkin/

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}



